version: '3.3'

services:
  app:
    depends_on:
      - app_db
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: wp-graphql-persisted-queries:latest-wp${WP_VERSION}-php${PHP_VERSION}
    volumes:
      - '.:/var/www/html/wp-content/plugins/wp-graphql-persisted-queries'
      - './.log/app:/var/log/apache2'
      - './local-wp-graphql:/var/www/html/wp-content/plugins/wp-graphql'
    env_file:
      - .env
    environment:
      USING_XDEBUG: ${USING_XDEBUG:-}
    ports:
      - '8091:80'
    networks:
      local:

  app_db:
    image: mariadb:10.2
    env_file:
      - .env
    ports:
      - '3306'
    networks:
      local:

  testing:
    depends_on:
      - app_db
    build:
      context: .
      dockerfile: docker/Dockerfile.testing
    image: wp-graphql-persisted-queries-testing:latest-wp${WP_VERSION}-php${PHP_VERSION}
    volumes:
      - '.:/var/www/html/wp-content/plugins/wp-graphql-persisted-queries'
      - './local-wp-graphql:/var/www/html/wp-content/plugins/wp-graphql'
    env_file:
      - .env
    environment:
      WP_URL: http://localhost
      USING_XDEBUG: ${USING_XDEBUG:-}
    networks:
      local:

networks:
  local:
