name: Tests - WordPress

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    name: WordPress Integration Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build container image
        run: |
          cp .env.dist .env
          docker-compose build \
            --build-arg WP_VERSION=5.6 \
            --build-arg PHP_VERSION=7.4 \
            --build-arg DOCKER_REGISTRY=ghcr.io/wp-graphql/

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Get Composer Cache Directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install

      - name: Run phpunit script
        run: docker-compose run testing
        env:
          WP_VERSION: 5.7.2
          PHP_VERSION: 7.4
          SUITES: acceptance

      - name: Run php code sniffer
        run: ./vendor/bin/phpcs
