name: Tests - WordPress

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    name: WordPress ${{ matrix.wordpress }} Integration Tests on PHP ${{ matrix.php }}
    strategy:
      matrix:
        php: [ '8.0', '7.4' ]
        wordpress: [ '5.7.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build container image
        env:
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
        run: |
          docker-compose build \
            --build-arg WP_VERSION=${{ matrix.wordpress }} \
            --build-arg PHP_VERSION=${{ matrix.php }} \
            --build-arg DOCKER_REGISTRY=ghcr.io/wp-graphql/

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Get Composer Cache Directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: php-${{ matrix.php }}-${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ matrix.php }}-${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install

      - name: Run acceptance, functional tests
        run: docker-compose run -e DEBUG=1 testing
        env:
          WP_VERSION: ${{ matrix.wordpress }}
          PHP_VERSION: ${{ matrix.php }}
          SUITES: use value from .env

      - name: Run php code sniffer
        run: ./vendor/bin/phpcs
