name: Tests - WordPress

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    name: WordPress ${{ matrix.wordpress }} Integration Tests on PHP ${{ matrix.php }}
    strategy:
      matrix:
        php: [ '8.0', '7.4' ]
        wordpress: [ '5.9', '5.8', '5.7.2', '5.6' ]
        # 1.14.5 had some changes to the Query Analyzer that broke some tests.
        # this is a stop-gap until we are able to address that
        wpgraphql: [ 'latest', '1.14.4' ]
        include:
          - php: '8.0'
            wordpress: '6.0'
          - php: '8.1'
            wordpress: '6.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build container image
        env:
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
        run: |
          docker-compose build \
            --build-arg WP_VERSION=${{ matrix.wordpress }} \
            --build-arg PHP_VERSION=${{ matrix.php }} \
            --build-arg DOCKER_REGISTRY=ghcr.io/wp-graphql/
            --build-arg WPGRAPHQL_VERSION=${{ matrix.wpgraphql }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Get Composer Cache Directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: php-${{ matrix.php }}-${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ matrix.php }}-${{ runner.os }}-composer-

      - name: Composer update dependencies
        run: composer update

      - name: Run acceptance, functional tests
        run: docker-compose run -e DEBUG=1 testing
        env:
          WP_VERSION: ${{ matrix.wordpress }}
          PHP_VERSION: ${{ matrix.php }}
          WPGRAPHQL_VERSION: ${{ matrix.wpgraphql }}
          SUITES: use value from .env
