name: Build plugin zip file
on:
  release:
    types: [ published ]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer
      - name: Install PHP dependencies
        run: |
          composer install --no-dev --optimize-autoloader
      - name: Create Artifact
        # Create a zip file similar to 10up/action-wordpress-plugin-deploy action
        run: |
          mkdir wpgraphql-smart-cache
          rsync -rc --exclude-from=.distignore . wpgraphql-smart-cache/ --delete --delete-excluded 
          zip -r wpgraphql-smart-cache.zip wpgraphql-smart-cache
          rm -rf wpgraphql-smart-cache
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wpgraphql-smart-cache
          path: wpgraphql-smart-cache.zip
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: wpgraphql-smart-cache.zip
